title: ğŸ‘¨ğŸ»ğŸ‘¦ğŸ» çˆ¶ä¸å­
author:
  name: éƒ‘å›½å’Œï¼Œéƒ‘æ–¹è¾¾
  email: fangda.zheng@gmail.com
description: >
  Father and son. çˆ¶ä¸å­çš„å¯¹è¯ã€‚

show_excerpts: false

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github: fuyuzi

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
